name: Build, Test, and Publish

on: 
  pull_request:
    branches:
      [main]
  
  push:
    branches:
      [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      key: ${{ steps.cache-key.outputs.KEY }}
      restore-keys: ${{ steps.cache-key.outputs.RESTORE_KEYS }}

    steps:
      - name: Setup NodeJS Version 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
      
      - name: Generate build cache key
        id: cache-key
        env: 
          KEY: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          RESTORE_KEYS: ${{ runner.os }}-node${{ matrix.node-version }}-
        run: |
          echo "KEY=${KEY}" >> "$GITHUB_OUTPUT"
          echo "RESTORE_KEYS=${RESTORE_KEYS}" >> "$GITHUB_OUTPUT"
      
      - name: Add build to cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ steps.cache-key.outputs.KEY }}
          restore-keys: | 
            ${{ steps.cache-key.outputs.RESTORE_KEYS }}
  
  security-tests:
    needs:
      - build
    uses: thedave42-fabrikam/common-workflows/.github/workflows/security-testing.yaml@main
    with:
      key: ${{ needs.build.outputs.key }}
      restore-keys: ${{ needs.build.outputs.restore-keys }}
      event-name: ${{ github.event_name }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: 
      - build

    steps:
      - name: Setup NodeJS Version 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ needs.build.outputs.key }}
          restore-keys: | 
            ${{ needs.build.outputs.restore-keys }}

      - name: Run tests
        run: |
          npm test

      - name: Upload test results
        if: always()
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Test Results
          path: test-results.json
          reporter: mocha-json
    
    

  publish-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build
      - unit-tests
      - security-tests

    steps:
      - name: Setup NodeJS Version 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ needs.build.outputs.key }}
          restore-keys: | 
            ${{ needs.build.outputs.restore-keys }}

      - name: Publish code
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload details if failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: publish-details
          path: |
            /home/runner/.npm/*
            /home/runner/.npmrc            



